<template>
    <div ref="container">
        <nav-bar></nav-bar>

        <div class="container main">
            <hr />
            <h2>Wedding Gallery</h2>
            <hr />
        </div>

        <div class="container main">
            <masonry :images="images"></masonry>
        </div>

        <footer-nav></footer-nav>
    </div>
</template>

<script>
import Vue from "vue";

import NavBar from "../../components/navbar.vue";
import FooterNav from "../../components/footer.vue";
import Masonry from "../../components/masonry.vue";

export default {
    components: {
        NavBar,
        FooterNav,
        Masonry,
    },
    data() {
        return {
            images: [
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-14-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-14.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-02-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-02.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-03-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-03.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-04-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-04.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-05-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-05.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-06-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-06.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-07-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-07.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-08-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-08.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-09-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-09.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-10-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-10.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-11-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-11.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-12-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-12.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-13-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-13.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-01-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-01.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-15-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-15.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-16-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-16.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-17-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-17.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-18-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-18.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-19-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-19.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-20-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-20.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-21-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-21.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-22-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-22.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-23-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-23.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-24-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-24.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-25-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-25.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-26-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-26.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-27-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-27.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-28-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-28.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-29-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-29.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-30-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-30.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-31-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-31.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-32-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-32.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-33-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-33.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-34-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-34.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-35-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-35.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-36-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-36.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-37-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-37.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-38-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-38.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-39-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-39.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-40-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-40.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-41-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-41.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-42-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-42.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-43-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-43.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-44-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-44.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-45-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-45.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-46-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-46.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-47-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-47.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-48-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-48.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-49-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-49.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-50-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-50.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-51-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-51.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-52-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-52.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-53-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-53.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-54-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-54.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-55-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-55.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-56-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-56.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-57-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-57.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-58-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-58.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-59-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-59.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-60-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-60.jpg",
                },
            ],
        };
    },
};
</script>

<style></style>
