<template>
    <div ref="container">
        <nav-bar></nav-bar>

        <div class="container main">
            <hr />
            <h2>Wedding Gallery</h2>
            <hr />
        </div>

        <div class="container main">
            <masonry :images="images"></masonry>
        </div>

        <footer-nav></footer-nav>
    </div>
</template>

<script>
import Vue from "vue";

import NavBar from "../../components/navbar.vue";
import FooterNav from "../../components/footer.vue";
import Masonry from "../../components/masonry.vue";

export default {
    components: {
        NavBar,
        FooterNav,
        Masonry,
    },
    data() {
        return {
            images: [
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-14-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-14-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-02-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-02-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-03-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-03-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-04-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-04-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-05-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-05-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-06-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-06-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-07-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-07-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-08-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-08-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-09-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-09-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-10-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-10-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-11-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-11-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-12-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-12-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-13-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-13-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-01-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-01-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-15-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-15-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-16-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-16-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-17-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-17-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-18-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-18-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-19-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-19-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-20-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-20-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-21-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-21-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-22-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-22-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-23-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-23-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-24-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-24-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-25-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-25-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-26-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-26-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-27-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-27-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-28-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-28-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-29-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-29-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-30-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-30-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-31-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-31-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-32-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-32-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-33-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-33-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-34-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-34-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-35-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-35-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-36-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-36-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-37-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-37-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-38-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-38-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-39-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-39-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-40-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-40-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-41-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-41-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-42-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-42-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-43-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-43-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-44-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-44-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-45-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-45-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-46-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-46-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-47-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-47-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-48-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-48-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-49-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-49-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-50-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-50-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-51-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-51-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-52-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-52-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-53-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-53-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-54-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-54-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-55-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-55-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-56-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-56-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-57-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-57-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-58-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-58-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-59-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-59-full.jpg",
                },
                {
                    url:
                        "/img/weddings/Knoxville_Wedding_Photographer-60-full.jpg",
                    preview:
                        "/img/weddings/Knoxville_Wedding_Photographer-60-full.jpg",
                },
            ],
        };
    },
};
</script>

<style></style>
