name: jellisonphoto.web
services:
  - build_command: npm run build
    environment_slug: node-js
    github:
      branch: master
      deploy_on_push: true
      repo: jellison/jellisonphoto.web
    name: jellisonphoto.web
